from __future__ import annotations

from app.services.link_check.constants import PLATFORM_BAIDU, PLATFORM_QUARK
from app.services.link_check.platforms import canonicalize_platform_name


SUPPORTED_TRANSFER_PLATFORMS = (
    PLATFORM_BAIDU,
    PLATFORM_QUARK,
)

SUPPORTED_TRANSFER_PLATFORM_SET = set(SUPPORTED_TRANSFER_PLATFORMS)

ALLOWED_TRANSFER_ACCOUNT_AUTH_TYPES = {"cookie"}
ALLOWED_TRANSFER_SHARE_MODES = {"private", "public"}
ALLOWED_TRANSFER_SELECTION_MODES = {"recent_messages", "time_range"}
ALLOWED_TRANSFER_DIRECTIONS = {"newest_first", "oldest_first"}

PAN_TRANSFER_BATCH_STATUS_DRAFT = "draft"
PAN_TRANSFER_BATCH_STATUS_RUNNING = "running"
PAN_TRANSFER_BATCH_STATUS_CANCELLED = "cancelled"
PAN_TRANSFER_BATCH_STATUS_COMPLETED = "completed"
PAN_TRANSFER_BATCH_STATUS_COMPLETED_WITH_ERRORS = "completed_with_errors"
PAN_TRANSFER_BATCH_STATUS_FAILED = "failed"

PAN_TRANSFER_ITEM_STATUS_QUEUED = "queued"
PAN_TRANSFER_ITEM_STATUS_PROCESSING = "processing"
PAN_TRANSFER_ITEM_STATUS_RETRY_WAIT = "retry_wait"
PAN_TRANSFER_ITEM_STATUS_COMPLETED = "completed"
PAN_TRANSFER_ITEM_STATUS_FAILED = "failed"

PAN_TRANSFER_SHARE_STATUS_PENDING = "pending"
PAN_TRANSFER_SHARE_STATUS_SHARED = "shared"
PAN_TRANSFER_SHARE_STATUS_FAILED = "failed"

PAN_TRANSFER_VALIDATION_STATUS_PENDING = "pending"
PAN_TRANSFER_VALIDATION_STATUS_VALID = "valid"
PAN_TRANSFER_VALIDATION_STATUS_WARNING = "warning"
PAN_TRANSFER_VALIDATION_STATUS_INVALID = "invalid"
PAN_TRANSFER_VALIDATION_STATUS_ERROR = "error"

PAN_TRANSFER_REPLACEMENT_STATUS_PENDING = "pending"
PAN_TRANSFER_REPLACEMENT_STATUS_REPLACED = "replaced"
PAN_TRANSFER_REPLACEMENT_STATUS_FAILED = "failed"

PAN_TRANSFER_ACTIVE_ITEM_STATUSES = {
    PAN_TRANSFER_ITEM_STATUS_QUEUED,
    PAN_TRANSFER_ITEM_STATUS_PROCESSING,
    PAN_TRANSFER_ITEM_STATUS_RETRY_WAIT,
}

DEFAULT_PAN_TRANSFER_MAX_ATTEMPTS = 3
DEFAULT_PAN_TRANSFER_RETRY_DELAY_SECONDS = 10 * 60
DEFAULT_PAN_TRANSFER_STALE_LOCK_SECONDS = 20 * 60

TRANSFER_LINK_HEALTH_LABELS = {
    "healthy": "正常",
    "invalid": "失效",
    "unknown": "未知",
}


def normalize_transfer_platform(platform: str) -> str:
    normalized = canonicalize_platform_name(str(platform or "").strip())
    if normalized not in SUPPORTED_TRANSFER_PLATFORM_SET:
        raise ValueError("unsupported transfer platform")
    return normalized
